//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugManagementSystemWebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public int DrugId { get; set; }
        public string C_Short_name { get; set; }
        public string C_Long_name_ { get; set; }
        public string C_Description_ { get; set; }
        public string C_Chemical_analysis { get; set; }
    }
}
